//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmFlow.Client.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FilmFlow.Client.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age Rating.
        /// </summary>
        public static string AgeRating {
            get {
                return ResourceManager.GetString("AgeRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse movies.
        /// </summary>
        public static string BrowseMovies {
            get {
                return ResourceManager.GetString("BrowseMovies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card number.
        /// </summary>
        public static string CardNumber {
            get {
                return ResourceManager.GetString("CardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserved chairs.
        /// </summary>
        public static string ChairsReserved {
            get {
                return ResourceManager.GetString("ChairsReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your seats.
        /// </summary>
        public static string ChooseYourSeats {
            get {
                return ResourceManager.GetString("ChooseYourSeats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cinema Hall.
        /// </summary>
        public static string CinemaHall {
            get {
                return ResourceManager.GetString("CinemaHall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create reservation.
        /// </summary>
        public static string CreateReservation {
            get {
                return ResourceManager.GetString("CreateReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit card.
        /// </summary>
        public static string CreditCard {
            get {
                return ResourceManager.GetString("CreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration date.
        /// </summary>
        public static string ExpDate {
            get {
                return ResourceManager.GetString("ExpDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hall.
        /// </summary>
        public static string Hall {
            get {
                return ResourceManager.GetString("Hall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience the magic of cinema like never before at FilmFlow, where every frame tells a story and every moment takes you on a journey..
        /// </summary>
        public static string IntroText1 {
            get {
                return ResourceManager.GetString("IntroText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading upcoming shows....
        /// </summary>
        public static string LoadingUpcomingShows {
            get {
                return ResourceManager.GetString("LoadingUpcomingShows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More about this movie.
        /// </summary>
        public static string MoreAboutThisMovie {
            get {
                return ResourceManager.GetString("MoreAboutThisMovie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movies.
        /// </summary>
        public static string Movies {
            get {
                return ResourceManager.GetString("Movies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name on card.
        /// </summary>
        public static string NameOnCard {
            get {
                return ResourceManager.GetString("NameOnCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate to FilmFlow.
        /// </summary>
        public static string NavigateToFilmFlow {
            get {
                return ResourceManager.GetString("NavigateToFilmFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No more upcoming shows.
        /// </summary>
        public static string NoMoreShows {
            get {
                return ResourceManager.GetString("NoMoreShows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No movies matching your search criterea.
        /// </summary>
        public static string NoMoviesMatchinYourSearchCriterea {
            get {
                return ResourceManager.GetString("NoMoviesMatchinYourSearchCriterea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay with credit card.
        /// </summary>
        public static string PayCreditCard {
            get {
                return ResourceManager.GetString("PayCreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay with iDeal.
        /// </summary>
        public static string PayIdeal {
            get {
                return ResourceManager.GetString("PayIdeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        public static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay now.
        /// </summary>
        public static string PayNow {
            get {
                return ResourceManager.GetString("PayNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation.
        /// </summary>
        public static string Reservation {
            get {
                return ResourceManager.GetString("Reservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This reservation is already paid for. You can view the tickets..
        /// </summary>
        public static string ReservationAlreadyPaid {
            get {
                return ResourceManager.GetString("ReservationAlreadyPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation created with ID {0}.
        /// </summary>
        public static string ReservationCreated {
            get {
                return ResourceManager.GetString("ReservationCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation of reservation failed.
        /// </summary>
        public static string ReservationCreationFailed {
            get {
                return ResourceManager.GetString("ReservationCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation not paid yet!.
        /// </summary>
        public static string ReservationNotPaidYet {
            get {
                return ResourceManager.GetString("ReservationNotPaidYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation number.
        /// </summary>
        public static string ReservationNr {
            get {
                return ResourceManager.GetString("ReservationNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservations.
        /// </summary>
        public static string Reservations {
            get {
                return ResourceManager.GetString("Reservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserve now.
        /// </summary>
        public static string ReserveNow {
            get {
                return ResourceManager.GetString("ReserveNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row.
        /// </summary>
        public static string Row {
            get {
                return ResourceManager.GetString("Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for movies.
        /// </summary>
        public static string SearchForMovies {
            get {
                return ResourceManager.GetString("SearchForMovies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seat.
        /// </summary>
        public static string Seat {
            get {
                return ResourceManager.GetString("Seat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seats planned.
        /// </summary>
        public static string SeatsPlanned {
            get {
                return ResourceManager.GetString("SeatsPlanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secret movie.
        /// </summary>
        public static string SecretMovie {
            get {
                return ResourceManager.GetString("SecretMovie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security code.
        /// </summary>
        public static string SecurityCode {
            get {
                return ResourceManager.GetString("SecurityCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select age rating.
        /// </summary>
        public static string SelectAgeRating {
            get {
                return ResourceManager.GetString("SelectAgeRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select category.
        /// </summary>
        public static string SelectCategory {
            get {
                return ResourceManager.GetString("SelectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select language.
        /// </summary>
        public static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children.
        /// </summary>
        public static string TarriffType_CHILDREN {
            get {
                return ResourceManager.GetString("TarriffType.CHILDREN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string TarriffType_NORMAL {
            get {
                return ResourceManager.GetString("TarriffType.NORMAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secret.
        /// </summary>
        public static string TarriffType_SECRET {
            get {
                return ResourceManager.GetString("TarriffType.SECRET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 65+.
        /// </summary>
        public static string TarriffType_SENIORS {
            get {
                return ResourceManager.GetString("TarriffType.SENIORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students.
        /// </summary>
        public static string TarriffType_STUDENTS {
            get {
                return ResourceManager.GetString("TarriffType.STUDENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets.
        /// </summary>
        public static string Tickets {
            get {
                return ResourceManager.GetString("Tickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming show.
        /// </summary>
        public static string UpcomingShow {
            get {
                return ResourceManager.GetString("UpcomingShow", resourceCulture);
            }
        }
    }
}
